name: Check for new Mimir releases
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0,4,8,12,16,20 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  check:
    name: Detect new releases
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo snap install yq

      - id: latest-release
        uses: pozetroninc/github-action-get-latest-release@v0.6.0
        with:
          repository: grafana/mimir
          excludes: prerelease, draft

      - name: Checkout the ROCK source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - id: check
        name: Check for new releases
        run: |
          release=$(yq .version rockcraft.yaml)          
          if [ "${release}" != "${{steps.latest-release.outputs.release}}" ]; then
            echo "release=${release}" >> $GITHUB_OUTPUT
            echo "New upstream release ${{steps.latest-release.outputs.release}} found"
          else
            echo "No new upstream release found"
          fi
      
      - name: Update the version file and push a branch
        if: ${{ steps.check.outputs.release != '' }}
        run: |
          version = "${{steps.latest-release.outputs.release}}"
          yq '.version = strenv(version) | .parts.mimir["source-tag"] = "mimir-" + strenv(version)")' rockcraft.yaml > rockcraft.yaml

      - name: Create a PR
        uses: peter-evans/create-pull-request@v4.2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): bump mimir version to ${{ steps.check.outputs.release }}"
          committer: "Github Actions <github-actions@github.com>"
          author: "Github Actions <github-actions@github.com>"
          title: "Update to Mimir ${{ steps.check.outputs.release }}"
          body: Automated update to follow upstream [release](https://github.com/grafana/mimir/releases/tag/${{ steps.check.outputs.release }}) of Mimir.
          branch: "chore/bump-version-to-${{ steps.check.outputs.release }}"
          delete-branch: true
